# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        architecture: x64
        python-version: 3.8
    - name: Set up JDK8
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '1.8'
        architecture: x64
        targets: 'JAVA_8_HOME'
    - name: Set up JDK 16
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '16'
        architecture: x64
    - name: Inspect environment
      run: |
        set | grep JAVA
    - name: Test
      run: mvn test -B -V -e --settings .mvn/custom-settings.xml
    - name: Build Python package
      run: python setup.py sdist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: prokaryote-2.4.2.tar.gz
        path: dist/
    
    
